export default [
  {
    id: 1,
    imgUrl: "../../../public/assets/images/1.png",
    category: "TECH",
    title: "V7 Digital Photo",
    author: "Caroline",
  },
  {
    id: 2,
    imgUrl: "../../../public/assets/images/2.png",
    category: "TECH",
    title: "V7 Digital Photo",
    author: "Caroline",
  },
  {
    id: 3,
    imgUrl: "../../../public/assets/images/3.png",
    category: "TECH",
    title: "V7 Digital Photo",
    author: "Caroline",
  },
  {
    id: 4,
    imgUrl: "../../../public/assets/images/4.png",
    category: "TECH",
    title: "V7 Digital Photo",
    author: "Caroline",
  },
  {
    id: 5,
    imgUrl: "../../../public/assets/images/5.png",
    category: "TECH",
    title: "V7 Digital Photo",
    author: "Caroline",
  },
  {
    id: 6,
    imgUrl: "../../../public/assets/images/1.png",
    category: "TECH",
    title: "V7 Digital Photo",
    author: "Caroline",
  },
  {
    id: 7,
    imgUrl: "../../../public/assets/images/2.png",
    category: "TECH",
    title: "V7 Digital Photo",
    author: "Caroline",
  },
  {
    id: 8,
    imgUrl: "../../../public/assets/images/3.png",
    category: "TECH",
    title: "V7 Digital Photo",
    author: "Caroline",
  },
];
